apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-prata
spec:
  hard:
    pods: "60"

---
apiVersion: apps/v1
kind: LimitRange
metadata:
  name: limit-range-prata
spec:
  limits:
  - type: Container
    max:
      memory: "2Gi"
      cpu: "2"
    min:
      memory: "256Mi"
      cpu: "0.1"

---
apiVersion: v1
kind: NodeSelector
metadata:
  name: node-selector-prata
spec:
  matchExpressions:
    - key: "profile"
      operator: In
      values:
        - prata