apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-bronze
spec:
  hard:
    pods: "30"

---
apiVersion: apps/v1
kind: LimitRange
metadata:
  name: limit-range-bronze
spec:
  limits:
  - type: Container
    max:
      memory: "1Gi"
      cpu: "1"
    min:
      memory: "512Mi"
      cpu: "0.1"

---
apiVersion: v1
kind: NodeSelector
metadata:
  name: node-selector-bronze
spec:
  matchExpressions:
    - key: "profile"
      operator: In
      values:
        - bronze