apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-ouro
spec:
  hard:
    pods: "90"

---
apiVersion: apps/v1
kind: LimitRange
metadata:
  name: limit-range-ouro
spec:
  limits:
  - type: Container
    max:
      memory: "4Gi"
      cpu: "4"
    min:
      memory: "1Gi"
      cpu: "0.1"

---
apiVersion: v1
kind: NodeSelector
metadata:
  name: node-selector-ouro
spec:
  matchExpressions:
    - key: "profile"
      operator: In
      values:
        - ouro